spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio-db
    username: postgres
    password: N@$$2018!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate: 
      dialect: org.hibernate.dialect.ProgressDialect
      generate-ddl: true
      show-sql: true
      dll-auto: update
    